# The prefix to be used for the Redis key under which file will be uploaded to Redis. The Redis key will be a
# combination of the `key_prefix` and the `revision_key`. Typically this is the `project.name` property from the
# deployment context and `:index` at the end. By default this option will be `ember-cli-deploy-rack:index`.
# For more details, see <https://github.com/ember-cli-deploy/ember-cli-deploy-redis#keyprefix>.
# key_prefix: 'ember-cli-deploy-rack:index'

# The suffix to be used for the Redis key under which the activated revision content will be stored in Redis. By default
# this option will be `current-content`. This makes the default activated revision in Redis looks like:
# The `project.name` property from the deployment and `:index:current-content` at the end.
# For more details, see <https://github.com/ember-cli-deploy/ember-cli-deploy-redis#activecontentsuffix>.
# active_content_suffix: 'current-content'

revision:
  # The regular expression the check the revision. By default this option will be `^[0-9a-f]{32}$`.
  # regexp: '^[0-9a-f]{32}$'

redis:
  # For available options see `Redis::Client::DEFAULTS`.
  # url: 'redis://<PASSWORD>@<HOST>:<PORT>/<DATABASE>'